### ISSUE TITLE
Generation of configuration files for ESGF

### ISSUE THREAD

**Issue by jesusff** [WCRP-CORDEX/cordex-cmip6-cv#165]
In order for ESGF to publish CORDEX-CMIP6 data, we need to provide two configuration files with information which can be built from the CV in this repo:
 * A `esg.cordex-cmip6.ini` file, which can be based either on [esg.cordex.ini](https://github.com/ESGF/config/blob/master/publisher-configs/ini/esg.cordex.ini) or [esg.cmip6.ini](https://github.com/ESGF/config/blob/master/publisher-configs/ini/esg.cmip6.ini). This is necessary for esgmapfile tool and esgprep package.
 * A JSON file, available from https://esg-publisher.readthedocs.io/en/main/install.html#project-configuration and needed for the new ESGF1.5

**Comment by larsbuntemeyer** [comment]
Ok, i think this is doable from our collection of meta data in the CV. Will you need some help with this? I see you have already a branch...

**Comment by jesusff** [comment]
Thank you. I still need to adapt the ini file to all the new CV elements. The script already replaces correctly the required lists and maps using the CV files, so it should work.

**Comment by jesusff** [comment]
For the record, @sashakames gave further info on the YAML file:

> As far as the publisher goes, there are several items that get configured now in the .yaml file.  You can customize the DRS global and constant attributes to be applied.
>
> Attached is some sample.yaml.
>
> And in the documentation: https://esg-publisher.readthedocs.io/en/main/install.html#config-file-esg-yaml

```yaml
user_project_config:
  cmip6plus:
    CONST_ATTR:
      project: CMIP6Plus
    pid_prefix: '21.14100'
  samplesec:
    CONST_ATTR:
      project: sampleSEC
    DRS:
      - project
      - source_id
      - experiment_id
      - frequency
      - variable_id
  cosmo-rea:
    CONST_ATTR:
      project: COSMO-REA
    DRS:
    - project
    - product
    - domain
    - institute
    - driving_model
    - experiment
    - ensemble
    - rcm_name
    - rcm_version
    - time_frequency
    - realm
    - variable_id
```
